# Generated by Django 3.1.7 on 2023-02-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Next',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('img', models.ImageField(upload_to='pics')),
                ('descn', models.TextField()),
            ],
        ),
    ]
